import Image from "next/image";
import Link from "next/link";
import { ArrowDownRight, ArrowRight, Plus } from "@phosphor-icons/react/dist/ssr";
import { PRODUCTS } from "@backend/catalog/catalog-data";
import { AuroraOrbit } from "@/components/react-bits/aurora-orbit";
import { ProductCard } from "@/components/product-card";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

// Home composition uses a split hero, a product grid and an editorial brand story.
export default function HomePage() {
  return <><SiteHeader /><main>
    <section className="relative overflow-hidden bg-ink text-white"><AuroraOrbit /><div className="relative mx-auto grid min-h-[620px] max-w-[1400px] items-center gap-12 px-5 py-16 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:px-12 lg:py-20"><div className="max-w-xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-white/55">Nueva colección · 2026</p><h1 className="mt-7 font-display text-5xl font-bold leading-[.98] tracking-[-.08em] sm:text-7xl">Viste lo que<br /><span className="text-accent">te mueve.</span></h1><p className="mt-7 max-w-sm text-base leading-7 text-white/65">Esenciales contemporáneos pensados para acompañar tu ritmo, no para marcarlo.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/catalogo" className="inline-flex items-center gap-2 bg-accent px-5 py-3.5 text-sm font-semibold text-white transition-colors hover:bg-white hover:text-ink">Explorar la colección <ArrowRight size={18} /></Link><Link href="#historia" className="inline-flex items-center gap-2 border border-white/25 px-5 py-3.5 text-sm font-medium text-white hover:border-white">Nuestra mirada <ArrowDownRight size={17} /></Link></div></div><div className="relative z-10 ml-auto w-full max-w-[560px]"><div className="relative aspect-[4/5] overflow-hidden bg-slate-800"><Image src={PRODUCTS[1].image} alt="Persona usando el pantalón Ruta de Jhorce" fill priority sizes="(max-width: 1024px) 90vw, 45vw" className="object-cover" /></div><div className="absolute -bottom-5 -left-5 bg-white px-5 py-4 text-ink shadow-2xl sm:-left-8"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-500">Pieza del mes</p><p className="mt-1 font-display text-lg font-semibold">Pantalón Ruta</p><p className="mt-1 text-xs text-slate-500">Diseñado para moverte</p></div></div></div></section>
    <section className="mx-auto max-w-[1400px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-accent">La selección</p><h2 className="mt-4 font-display text-4xl font-bold tracking-[-.07em] sm:text-5xl">Lo que más se mueve</h2></div><Link href="/catalogo" className="inline-flex items-center gap-2 text-sm font-semibold hover:text-accent">Ver toda la tienda <ArrowRight size={17} /></Link></div><div className="mt-10 grid grid-cols-2 gap-x-4 gap-y-10 md:grid-cols-4 lg:mt-14 lg:gap-x-6">{PRODUCTS.slice(0, 4).map((product) => <ProductCard key={product.id} product={product} />)}</div></section>
    <section id="historia" className="bg-white"><div className="mx-auto grid max-w-[1400px] items-center gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_1fr] lg:gap-24 lg:px-12 lg:py-28"><div className="relative aspect-[4/5] overflow-hidden bg-mist"><Image src={PRODUCTS[4].secondaryImage} alt="Textura y movimiento de una camisa Jhorce" fill sizes="(max-width: 1024px) 90vw, 45vw" className="object-cover" /><div className="absolute bottom-5 right-5 flex h-20 w-20 items-center justify-center rounded-full bg-accent text-center text-[10px] font-bold uppercase leading-4 tracking-[.12em] text-white">Hecho<br />para durar</div></div><div className="max-w-lg"><p className="text-xs font-bold uppercase tracking-[.2em] text-accent">Nuestra mirada</p><h2 className="mt-5 font-display text-4xl font-bold leading-[1.02] tracking-[-.07em] sm:text-6xl">Menos ruido.<br />Más intención.</h2><p className="mt-7 text-[15px] leading-7 text-slate-600">Creemos en piezas que se quedan. En materiales que mejoran con el uso. En diseñar menos, pero diseñar mejor.</p><p className="mt-5 text-[15px] leading-7 text-slate-600">Jhorce nace en Colombia para vestir los días reales: los que cambian de plan, de clima y de ritmo.</p><Link href="/catalogo" className="mt-9 inline-flex items-center gap-2 border-b border-ink pb-2 text-sm font-semibold hover:border-accent hover:text-accent">Conoce la colección <ArrowRight size={17} /></Link></div></div></section>
    <section className="mx-auto max-w-[1400px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="grid gap-4 md:grid-cols-3"><div className="bg-ink p-7 text-white md:col-span-2 md:p-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-white/45">La promesa</p><h2 className="mt-8 max-w-xl font-display text-3xl font-semibold tracking-[-.06em] sm:text-4xl">Tu armario también puede respirar.</h2><div className="mt-12 grid gap-5 border-t border-white/15 pt-6 text-sm text-white/65 sm:grid-cols-2"><p className="flex gap-3"><Plus size={18} className="shrink-0 text-accent" /> Diseños que combinan entre sí.</p><p className="flex gap-3"><Plus size={18} className="shrink-0 text-accent" /> Materiales elegidos para durar.</p></div></div><div className="bg-accent p-7 text-white md:p-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-white/70">¿Necesitas ayuda?</p><h3 className="mt-8 font-display text-3xl font-semibold tracking-[-.06em]">Hablemos de tu próximo look.</h3><Link href="/contacto" className="mt-12 inline-flex items-center gap-2 text-sm font-semibold underline underline-offset-8">Escríbenos <ArrowRight size={17} /></Link></div></div></section>
  </main><SiteFooter /></>;
}

