import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Plus } from "@phosphor-icons/react/dist/ssr";
import { PRODUCTS } from "@backend/catalog/catalog-data";
import { CategoryGrid } from "@/components/home/category-grid";
import { ProductCard } from "@/components/product-card";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { ScrollVideoBackground } from "@/components/motion/scroll-video-background";

// Home composition uses the real catalog as the visual source for a warm, editorial storefront.
export default function HomePage() {
  // The current range spans the full document; use startSelector/endSelector here to scope it to a future section.
  return <><ScrollVideoBackground src="/media/Jhorce.mp4" poster="/brand/about-byjhor.png" subjectPosition="50% 50%" range={{ start: 0 }} /><div className="relative z-10"><SiteHeader /><main>
    <section className="overflow-hidden border-b border-ink/10 bg-paper/90"><div className="site-shell grid items-center gap-10 py-10 sm:py-14 lg:grid-cols-[.9fr_1.1fr] lg:gap-20 lg:py-16"><div className="max-w-xl"><p className="eyebrow">Pelucas byjhor</p><h1 className="mt-5 max-w-lg font-display text-6xl font-semibold leading-[.88] tracking-[-.04em] sm:text-8xl">Tu esencia.<br /><span className="text-coral">Tu estilo.</span></h1><p className="mt-7 max-w-sm text-base leading-7 text-muted">Encuentra la peluca que acompaña tu estilo, tu ritmo y tu forma de verte.</p><Link href="/catalogo" className="button-primary mt-8">Ver las pelucas <ArrowRight size={18} /></Link><p className="mt-7 text-xs uppercase tracking-[.14em] text-muted">Largos, tonos y accesorios para elegir</p></div><figure className="m-0"><div className="relative rounded-[12px] bg-teal p-2.5 sm:p-4"><div className="relative aspect-[4/5] overflow-hidden rounded-[8px] bg-white"><Image src={PRODUCTS[1].image} alt="Imagen de referencia de Peluca Ruta" fill priority sizes="(max-width: 1024px) 100vw, 55vw" className="object-cover" /></div></div><figcaption className="flex items-center justify-between gap-4 border-b border-ink/15 py-4 text-sm"><span className="font-display text-xl font-semibold">Peluca Ruta</span><span className="text-muted">Explora este estilo</span></figcaption></figure></div></section>
    <CategoryGrid products={PRODUCTS} />
    <section className="site-shell py-16 sm:py-20 lg:py-24"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Selección byjhor</p><h2 className="section-title mt-3">Pelucas para explorar</h2></div><Link href="/catalogo" className="inline-flex items-center gap-2 text-sm font-semibold text-ink transition-colors hover:text-coral">Ver toda la tienda <ArrowRight size={17} /></Link></div><p className="mt-4 max-w-md text-sm leading-6 text-muted">Una selección de pelucas y accesorios para encontrar tu próximo look.</p><div className="mt-9 grid grid-cols-2 gap-x-4 gap-y-10 md:grid-cols-4 lg:mt-12 lg:gap-x-6">{PRODUCTS.slice(0, 4).map((product) => <ProductCard key={product.id} product={product} />)}</div></section>
    <section id="historia" className="border-y border-teal-deep/20 bg-teal text-paper"><div className="site-shell grid items-center gap-10 py-16 sm:py-20 lg:grid-cols-[1fr_1fr] lg:gap-20 lg:py-24"><figure className="m-0"><div className="relative rounded-[12px] bg-coral p-2.5 sm:p-4"><div className="relative aspect-[4/5] overflow-hidden rounded-[8px] bg-white"><Image src="/brand/about-byjhor.png" alt="Retrato editorial de una mujer con cabello afro" fill sizes="(max-width: 1024px) 100vw, 45vw" className="object-cover" /></div></div><figcaption className="pt-4 text-xs uppercase tracking-[.14em] text-paper/70">Inspiración byjhor</figcaption></figure><div className="max-w-lg"><p className="eyebrow text-sun">Sobre byjhor</p><h2 className="section-title mt-4 text-paper sm:text-6xl">Tu cabello.<br />Tus reglas.</h2><p className="mt-7 text-[15px] leading-7 text-paper/80">byjhor reúne pelucas y accesorios para que elegir cómo verte sea una decisión tuya.</p><p className="mt-5 text-[15px] leading-7 text-paper/80">Explora largos, tonos y estilos que pueden acompañarte en diferentes momentos.</p><Link href="/catalogo" className="mt-8 inline-flex items-center gap-2 border-b border-paper pb-2 text-sm font-semibold transition-colors hover:border-sun hover:text-sun">Ver las pelucas <ArrowRight size={17} /></Link></div></div></section>
    <section className="site-shell py-16 sm:py-20 lg:py-24"><div className="grid gap-5 rounded-[10px] bg-blush p-7 sm:p-10 lg:grid-cols-[1.2fr_.8fr] lg:p-14"><div><p className="eyebrow">Elige tu opción</p><h2 className="mt-4 max-w-xl font-display text-4xl font-semibold leading-[.95] tracking-[-.03em] sm:text-5xl">El largo y el tono que imaginas.</h2><div className="mt-9 grid gap-4 border-t border-ink/15 pt-6 text-sm text-muted sm:grid-cols-2"><p className="flex gap-3"><Plus size={18} className="shrink-0 text-coral" /> Largos para explorar.</p><p className="flex gap-3"><Plus size={18} className="shrink-0 text-coral" /> Tonos para cambiar.</p></div></div><div className="flex flex-col justify-between gap-7 border-t border-ink/15 pt-6 lg:border-l lg:border-t-0 lg:pl-10 lg:pt-0"><div><p className="eyebrow">¿Necesitas ayuda?</p><h3 className="mt-4 font-display text-3xl font-semibold leading-[.95]">Te ayudamos a elegir tu peluca.</h3></div><Link href="/contacto" className="inline-flex w-fit items-center gap-2 text-sm font-semibold text-ink underline underline-offset-8 transition-colors hover:text-coral">Escríbenos <ArrowRight size={17} /></Link></div></div></section>
  </main><SiteFooter /></div></>;
}
