import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Plus } from "@phosphor-icons/react/dist/ssr";
import { PRODUCTS } from "@backend/catalog/catalog-data";
import { CategoryGrid } from "@/components/home/category-grid";
import { ProductCard } from "@/components/product-card";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

// Home composition uses the real catalog as the visual source for a warm, editorial storefront.
export default function HomePage() {
  return <><SiteHeader /><main>
    <section className="border-b border-ink/10 bg-paper"><div className="site-shell grid items-center gap-10 py-10 sm:py-14 lg:grid-cols-[.9fr_1.1fr] lg:gap-20 lg:py-16"><div className="max-w-xl"><p className="eyebrow">Colección 2026</p><h1 className="mt-5 max-w-lg font-display text-6xl font-semibold leading-[.88] tracking-[-.04em] sm:text-8xl">Tu esencia.<br /><span className="text-gold-deep">Tu estilo.</span></h1><p className="mt-7 max-w-sm text-base leading-7 text-muted">Descubre prendas y accesorios para expresarte a tu manera.</p><Link href="/catalogo" className="button-primary mt-8">Explorar la colección <ArrowRight size={18} /></Link><p className="mt-7 text-xs uppercase tracking-[.14em] text-muted">Esenciales, movimiento y accesorios</p></div><figure className="m-0"><div className="relative aspect-[4/5] overflow-hidden rounded-[10px] bg-sand"><Image src={PRODUCTS[1].image} alt="Pantalón Ruta en movimiento" fill priority sizes="(max-width: 1024px) 100vw, 55vw" className="object-cover" /></div><figcaption className="flex items-center justify-between gap-4 border-b border-ink/15 py-4 text-sm"><span className="font-display text-xl font-semibold">Pantalón Ruta</span><span className="text-muted">Diseñado para moverte</span></figcaption></figure></div></section>
    <CategoryGrid products={PRODUCTS} />
    <section className="site-shell py-16 sm:py-20 lg:py-24"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Selección byjhor</p><h2 className="section-title mt-3">La selección byjhor</h2></div><Link href="/catalogo" className="inline-flex items-center gap-2 text-sm font-semibold text-ink transition-colors hover:text-accent-deep">Ver toda la tienda <ArrowRight size={17} /></Link></div><p className="mt-4 max-w-md text-sm leading-6 text-muted">Una edición de esenciales, movimiento y accesorios para expresarte a tu manera.</p><div className="mt-9 grid grid-cols-2 gap-x-4 gap-y-10 md:grid-cols-4 lg:mt-12 lg:gap-x-6">{PRODUCTS.slice(0, 4).map((product) => <ProductCard key={product.id} product={product} />)}</div></section>
    <section id="historia" className="border-y border-ink/10 bg-white"><div className="site-shell grid items-center gap-10 py-16 sm:py-20 lg:grid-cols-[1fr_1fr] lg:gap-20 lg:py-24"><figure className="m-0"><div className="relative aspect-[4/5] overflow-hidden rounded-[10px] bg-sand"><Image src={PRODUCTS[4].secondaryImage} alt="Textura y movimiento de una camisa Línea" fill sizes="(max-width: 1024px) 100vw, 45vw" className="object-cover" /></div><figcaption className="pt-4 text-xs uppercase tracking-[.14em] text-muted">Camisa Línea</figcaption></figure><div className="max-w-lg"><p className="eyebrow">Sobre byjhor</p><h2 className="section-title mt-4 sm:text-6xl">Menos ruido.<br />Más intención.</h2><p className="mt-7 text-[15px] leading-7 text-muted">Creemos en piezas que se quedan. En materiales que mejoran con el uso. En diseñar menos, pero diseñar mejor.</p><p className="mt-5 text-[15px] leading-7 text-muted">byjhor nace en Colombia para vestir los días reales: los que cambian de plan, de clima y de ritmo.</p><Link href="/catalogo" className="mt-8 inline-flex items-center gap-2 border-b border-ink pb-2 text-sm font-semibold transition-colors hover:border-accent-deep hover:text-accent-deep">Conoce la colección <ArrowRight size={17} /></Link></div></div></section>
    <section className="site-shell py-16 sm:py-20 lg:py-24"><div className="grid gap-5 rounded-[10px] bg-sand p-7 sm:p-10 lg:grid-cols-[1.2fr_.8fr] lg:p-14"><div><p className="eyebrow">Para todos los días</p><h2 className="mt-4 max-w-xl font-display text-4xl font-semibold leading-[.95] tracking-[-.03em] sm:text-5xl">Tu armario también puede respirar.</h2><div className="mt-9 grid gap-4 border-t border-ink/15 pt-6 text-sm text-muted sm:grid-cols-2"><p className="flex gap-3"><Plus size={18} className="shrink-0 text-gold-deep" /> Diseños que combinan entre sí.</p><p className="flex gap-3"><Plus size={18} className="shrink-0 text-gold-deep" /> Materiales elegidos para durar.</p></div></div><div className="flex flex-col justify-between gap-7 border-t border-ink/15 pt-6 lg:border-l lg:border-t-0 lg:pl-10 lg:pt-0"><div><p className="eyebrow">¿Necesitas ayuda?</p><h3 className="mt-4 font-display text-3xl font-semibold leading-[.95]">Hablemos de tu próximo look.</h3></div><Link href="/contacto" className="inline-flex w-fit items-center gap-2 text-sm font-semibold text-ink underline underline-offset-8 transition-colors hover:text-accent-deep">Escríbenos <ArrowRight size={17} /></Link></div></div></section>
  </main><SiteFooter /></>;
}
