"use client";

import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Minus, Plus, Trash } from "@phosphor-icons/react";
import { useCart } from "@/components/cart/cart-provider";
import { formatCop } from "@/lib/format";

// Cart summary keeps line edits and server-aligned shipping messaging in one reusable component.
export function CartSummary() {
  const { items, subtotal, updateQuantity, removeItem } = useCart();
  const shipping = subtotal >= 250000 || subtotal === 0 ? 0 : 16000;

  if (items.length === 0) return <div className="border border-ink/10 bg-white px-6 py-16 text-center"><p className="font-display text-2xl font-semibold tracking-[-.04em]">Tu carrito está esperando</p><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-slate-500">Guarda aquí esas piezas que hacen que vestirte se sienta más fácil.</p><Link href="/catalogo" className="mt-7 inline-flex bg-ink px-5 py-3 text-sm font-medium text-white hover:bg-accent">Explorar la tienda</Link></div>;

  return <div className="grid gap-10 lg:grid-cols-[1fr_360px] lg:gap-16"><div className="divide-y divide-ink/10 border-y border-ink/10">{items.map(({ product, quantity }) => <div key={product.id} className="grid grid-cols-[88px_1fr_auto] gap-4 py-5 sm:grid-cols-[112px_1fr_auto] sm:gap-5"><Image src={product.image} alt={product.name} width={112} height={140} className="aspect-[4/5] w-full object-cover" /><div><Link href={`/producto/${product.slug}`} className="font-display text-lg font-semibold hover:text-accent">{product.name}</Link><p className="mt-1 text-xs text-slate-500">{product.category}</p><p className="mt-3 text-sm font-medium">{formatCop(product.price)}</p><div className="mt-4 flex w-fit items-center border border-ink/15"><button onClick={() => updateQuantity(product.id, quantity - 1)} className="p-2" aria-label={`Disminuir ${product.name}`}><Minus size={14} /></button><span className="w-7 text-center text-xs">{quantity}</span><button onClick={() => updateQuantity(product.id, quantity + 1)} className="p-2" aria-label={`Aumentar ${product.name}`}><Plus size={14} /></button></div></div><div className="flex flex-col items-end justify-between"><p className="font-display text-sm font-semibold">{formatCop(product.price * quantity)}</p><button onClick={() => removeItem(product.id)} className="text-slate-400 transition-colors hover:text-ink" aria-label={`Eliminar ${product.name}`}><Trash size={17} weight="light" /></button></div></div>)}</div><aside className="h-fit bg-white p-6 sm:p-7"><p className="font-display text-xl font-semibold">Resumen</p><div className="mt-6 grid gap-3 border-b border-ink/10 pb-6 text-sm"><div className="flex justify-between"><span className="text-slate-500">Subtotal</span><span>{formatCop(subtotal)}</span></div><div className="flex justify-between"><span className="text-slate-500">Envío</span><span>{shipping === 0 ? "Gratis" : formatCop(shipping)}</span></div></div><div className="flex justify-between py-5 font-display text-lg font-semibold"><span>Total</span><span>{formatCop(subtotal + shipping)}</span></div><Link href="/checkout" className="flex items-center justify-center gap-2 bg-accent px-5 py-3.5 text-sm font-semibold text-white hover:bg-accent-deep">Continuar al checkout <ArrowRight size={17} /></Link><p className="mt-4 text-center text-[11px] leading-5 text-slate-400">Los precios finales y el stock se validan de nuevo en el servidor.</p></aside></div>;
}
