"use client";

import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Minus, Plus, Trash } from "@phosphor-icons/react";
import { getCartItemKey, useCart } from "@/components/cart/cart-provider";
import { getCategoryLabel, getColorLabel } from "@/lib/catalog-labels";
import { formatCop } from "@/lib/format";

// Cart summary keeps selected variants, line edits and server-aligned shipping messaging in one component.
export function CartSummary() {
  const { items, subtotal, updateQuantity, removeItem } = useCart();
  const shipping = subtotal >= 250000 || subtotal === 0 ? 0 : 16000;

  if (items.length === 0) return <div className="surface-panel px-6 py-16 text-center"><p className="font-display text-3xl font-semibold leading-none tracking-[-.02em]">Tu carrito está esperando</p><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-muted">Guarda aquí tu próxima peluca o los accesorios para cuidarla.</p><Link href="/catalogo" className="button-primary mt-7">Explorar la tienda</Link></div>;

  return <div className="grid gap-10 lg:grid-cols-[1fr_360px] lg:gap-16"><div className="divide-y divide-ink/10 border-y border-ink/10">{items.map((item) => { const { product, quantity } = item; const itemKey = getCartItemKey(item); const colorLabel = getColorLabel(product.category); return <div key={itemKey} className="grid grid-cols-[88px_1fr_auto] gap-4 py-5 sm:grid-cols-[112px_1fr_auto] sm:gap-5"><Image src={product.image} alt={`Imagen de referencia de ${product.name}`} width={112} height={140} className="aspect-[4/5] w-full rounded-[8px] object-cover" /><div><Link href={`/producto/${product.slug}`} className="font-display text-xl font-semibold leading-none transition-colors hover:text-accent-deep">{product.name}</Link><p className="mt-2 text-xs text-muted">{getCategoryLabel(product.category)}</p>{(item.size || item.color) && <p className="mt-2 text-xs text-muted">{item.size && `Largo ${item.size}`}{item.size && item.color && " / "}{item.color && `${colorLabel} ${item.color}`}</p>}<p className="mt-3 text-sm font-medium tabular-nums">{formatCop(product.price)}</p><div className="mt-4 flex w-fit items-center rounded-[8px] border border-ink/15"><button onClick={() => updateQuantity(itemKey, quantity - 1)} className="p-2 transition-colors hover:bg-sand" aria-label={`Disminuir ${product.name}`}><Minus size={14} /></button><span className="w-7 text-center text-xs tabular-nums">{quantity}</span><button onClick={() => updateQuantity(itemKey, quantity + 1)} className="p-2 transition-colors hover:bg-sand" aria-label={`Aumentar ${product.name}`}><Plus size={14} /></button></div></div><div className="flex flex-col items-end justify-between"><p className="font-body text-sm font-semibold tabular-nums">{formatCop(product.price * quantity)}</p><button onClick={() => removeItem(itemKey)} className="text-muted transition-colors hover:text-ink" aria-label={`Eliminar ${product.name}`}><Trash size={17} weight="light" /></button></div></div>; })}</div><aside className="surface-panel h-fit p-6 sm:p-7 lg:sticky lg:top-24"><p className="font-display text-2xl font-semibold">Resumen</p><div className="mt-6 grid gap-3 border-b border-ink/10 pb-6 text-sm"><div className="flex justify-between"><span className="text-muted">Subtotal</span><span className="tabular-nums">{formatCop(subtotal)}</span></div><div className="flex justify-between"><span className="text-muted">Envío</span><span>{shipping === 0 ? "Gratis" : formatCop(shipping)}</span></div></div><div className="flex justify-between py-5 font-display text-xl font-semibold"><span>Total</span><span className="tabular-nums">{formatCop(subtotal + shipping)}</span></div><Link href="/checkout" className="button-primary w-full">Continuar al checkout <ArrowRight size={17} /></Link><p className="mt-4 text-center text-[11px] leading-5 text-muted">Los precios finales y el stock se validan de nuevo en el servidor.</p></aside></div>;
}
